config/routes.rb
BiblioTrial1::Application.routes.draw do
  resources :books

  resources :worms

end

app/models/book.rb
class Book < ActiveRecord::Base
    belongs_to :worm
    
    validates :worm_id, :length => { :maximum => 3 }
    validates :genre, :length => { :maximum => 40 }
    validates :title, :length => { :maximum => 100 }
    validates :author, :length => { :maximum => 50 }
    validates :synopsis, :length => { :maximum => 500 }
end

app/models/worm.rb
class Worm < ActiveRecord::Base
    has_many :books
    
    validates :name, :length => { :maximum => 50 }
    validates :email, :length => { :maximum => 75 }
    validates :favorite_author, :length => { :maximum => 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.xml
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @books }
    end
  end

  # GET /books/1
  # GET /books/1.xml
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/new
  # GET /books/new.xml
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    render :layout => 'alt_application'
  end

  # POST /books
  # POST /books.xml
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to(@book, :notice => 'Book was successfully created.') }
        format.xml  { render :xml => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.xml
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to(@book, :notice => 'Book was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.xml
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to(books_url) }
      format.js { render :text => "alert('Book has been shredded')" }
    end
  end
end

app/controllers/worms_controller.rb
class WormsController < ApplicationController
    #layout 'mynewlayout'
    
  # GET /worms
  # GET /worms.xml
  def index
    @worms = Worm.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @worms }
    end
  end

  # GET /worms/1
  # GET /worms/1.xml
  def show
    @worm = Worm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @worm }
    end
  end

  # GET /worms/new
  # GET /worms/new.xml
  def new
    @worm = Worm.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @worm }
    end
  end

  # GET /worms/1/edit
  def edit
    @worm = Worm.find(params[:id])
      render :layout => 'alt_application'
  end

  # POST /worms
  # POST /worms.xml
  def create
    @worm = Worm.new(params[:worm])

    respond_to do |format|
      if @worm.save
        format.html { redirect_to(@worm, :notice => 'Worm was successfully created.') }
        format.xml  { render :xml => @worm, :status => :created, :location => @worm }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @worm.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /worms/1
  # PUT /worms/1.xml
  def update
    @worm = Worm.find(params[:id])

    respond_to do |format|
      if @worm.update_attributes(params[:worm])
        format.html { redirect_to(@worm, :notice => 'Worm was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @worm.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /worms/1
  # DELETE /worms/1.xml
  def destroy
    @worm = Worm.find(params[:id])
    @worm.destroy

    respond_to do |format|
      format.html { redirect_to(worms_url) }
      format.js { render :text => "alert('Worm has been squashed!')" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/worms_helper.rb
module WormsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Contributing Worm" %><br />
    <%= f.text_field :worm_id %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br />
    <%= f.text_field :synopsis %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Contributing worm</th>
    <th>Genre</th>
    <th>Title</th>
    <th>Author</th>
    <th>Synopsis</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.worm_id %></td>
    <td><%= book.genre %></td>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.synopsis %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Shred', book, :confirm => 'Are you sure you want to shred this book?', :method => :delete, :remote=>true %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contributing worm:</b>
  <%= @book.worm_id %>
</p>

<p>
  <b>Genre:</b>
  <%= @book.genre %>
</p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Synopsis:</b>
  <%= @book.synopsis %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %> 

app/views/layouts/alt_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblioworm!</title>
  <%= button_to 'Homepage', '/', :method => :get %>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblioworm!</title>
  <%= button_to 'Homepage', '/', :method => :get %>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>
| <%= link_to 'XML', request.request_uri+".xml" %>

</body>
</html>

app/views/worms/_form.html.erb
<%= form_for(@worm) do |f| %>
  <% if @worm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worm.errors.count, "error") %> prohibited this worm from being saved:</h2>

      <ul>
      <% @worm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :favorite_author %><br />
    <%= f.text_field :favorite_author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/worms/edit.html.erb
<h1>Editing worm</h1>

<%= render 'form' %>

<%= link_to 'Show', @worm %> |
<%= link_to 'Back', worms_path %>

app/views/worms/index.html.erb
<h1>Listing worms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Favorite author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @worms.each do |worm| %>
  <tr>
    <td><%= worm.name %></td>
    <td><%= worm.email %></td>
    <td><%= worm.favorite_author %></td>
    <td><%= link_to 'Show', worm %></td>
    <td><%= link_to 'Edit', edit_worm_path(worm) %></td>
    <td><%= link_to 'Squash', worm, :confirm => 'Are you sure you want to squash this worm?', :method => :delete, :remote=>true %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Worm', new_worm_path %>

app/views/worms/new.html.erb
<h1>New worm</h1>

<%= render 'form' %>

<%= link_to 'Back', worms_path %>

app/views/worms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @worm.name %>
</p>

<p>
  <b>Email:</b>
  <%= @worm.email %>
</p>

<p>
  <b>Favorite author:</b>
  <%= @worm.favorite_author %>
</p>


<%= link_to 'Edit', edit_worm_path(@worm) %> |
<%= link_to 'Back', worms_path %> 